[[redirects]]
  from = "https://nervous-almeida-4ca728.netlify.app/*"
  to = "https://docs.errata.ai/:splat"
  force = true

[[redirects]]
  from = "/vale/install"
  to = "https://vale.sh/docs/vale-cli/installation/"
  force = true
